config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only:[:new, :create, :destroy]
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  root to: 'destinations#index'
  match '/about', to: 'static_pages#about', via: 'get'

  resources :users
  resources :destinations
  post 'destinations/:id/favorite' => 'destinations#favorite'

end

app/models/destination.rb
class Destination < ActiveRecord::Base
  has_and_belongs_to_many :users
  validates :country, :books, presence: true
  geocoded_by :city
  after_validation :geocode

  def getInfoWindowHtml
    "<div><p>#{city}, #{country}</p>" +
    "<a href='/destinations/#{id}'>Get Book Suggestions</a></div>"
  end

  def self.get_author(book)
    response = HTTParty.get "https://www.goodreads.com/search.xml?key=sperNAdGlluygbFCKZqL3g&q=#{book.gsub(" ", "+")}"
    results = response["GoodreadsResponse"]["search"]["results"]
    # counter = 0
      if results && results["work"].is_a?(Array)
        url = results["work"][0]["best_book"]["author"]["name"]
        puts results
          if url.include?('nophoto')
            return results["work"][1]["best_book"]["author"]["name"]
          else
            return url
          end
      else
        'Not Found'
      end
    # counter++
  end

  def self.get_image_url(book)
    response = HTTParty.get "https://www.goodreads.com/search.xml?key=sperNAdGlluygbFCKZqL3g&q=#{book.gsub(" ", "+")}"
    results = response["GoodreadsResponse"]["search"]["results"]
    # counter = 0
      if results && results["work"].is_a?(Array)
        url = results["work"][0]["best_book"]["image_url"]

          if url.include?('nophoto')
            return results["work"][1]["best_book"]["image_url"]
          else
            return url
          end
      else
        'Not Found'
      end
    # counter++
  end
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :set_destination, only: [:show, :edit, :update, :destroy]

  # GET /destinations
  # GET /destinations.json
  def index
    @destinations = Destination.all
    @hash = Gmaps4rails.build_markers(@destinations) do |destination, marker|
      marker.lat destination.latitude
      marker.lng destination.longitude
      marker.infowindow "#{destination.getInfoWindowHtml}"
      marker.picture({
        :url     => "http://www2.psd100.com/ppp/2013/10/0501/Open-book-icon-1005102438.png",
        :width   => 32,
        :height  => 27
        })
    end
  end

  # GET /destinations/1
  # GET /destinations/1.json
  def show
  end

  def favorite
   destination = Destination.find(params[:id])
   current_user.destinations << destination.book
   current_user ? redirect_to(current_user) : redirect_to(signup_path)
  end

  # GET /destinations/new
  def new
    @destination = Destination.new
  end

  # GET /destinations/1/edit
  def edit
  end

  # POST /destinations
  # POST /destinations.json
  def create
    @destination = Destination.new(destination_params)
    @destination.user = current_user

    respond_to do |format|
      if @destination.save
        format.html { redirect_to @destination, notice: 'Destination was successfully created.' }
        format.json { render :show, status: :created, location: @destination }
      else
        format.html { render :new }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /destinations/1
  # PATCH/PUT /destinations/1.json
  def update
    respond_to do |format|
      if @destination.update(destination_params)
        format.html { redirect_to @destination, notice: 'Destination was successfully updated.' }
        format.json { render :show, status: :ok, location: @destination }
      else
        format.html { render :edit }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /destinations/1
  # DELETE /destinations/1.json
  def destroy
    @destination.destroy
    respond_to do |format|
      format.html { redirect_to destinations_url, notice: 'Destination was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_destination
      @destination = Destination.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def destination_params
      params.require(:destination).permit(:city, :country, :books, user_ids: [])
    end
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/views/destinations/_form.html.erb
<%= form_for(@destination) do |f| %>
  <% if @destination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@destination.errors.count, "error") %> prohibited this destination from being saved:</h2>

      <ul>
      <% @destination.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :books %><br>
    <%= f.text_field :books %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/destinations/edit.html.erb
<h1>Editing Destination</h1>

<%= render 'form' %>

<%= link_to 'Show', @destination %> |
<%= link_to 'Back', destinations_path %>

app/views/destinations/new.html.erb
<h1>New Destination</h1>

<%= render 'form' %>

<%= link_to 'Back', destinations_path %>

app/views/destinations/show.html.erb
<link href='https://fonts.googleapis.com/css?family=Josefin+Sans' rel='stylesheet' type='text/css'>

<p id="notice"><%= notice %></p>

<p class="bookInfo">
  <strong>City:</strong>
   <%= @destination.city %>
</p>

<p class="bookInfo">
  <strong>Country:</strong>
  <%= @destination.country %>
</p>

<p class="bookInfo">
  <strong>Books:</strong>
  <dl class="dl-horizontal">
  <dt><% @destination.books.each do |book| %>
    <dd><%= image_tag Destination.get_image_url(book) %><dd>
      <%= book %> -- By: <%= Destination.get_author(book) %>
      <%= form_tag(controller: "destinations", action: "favorite", method: "post") do %>
        <button type="submit" class="btn btn-danger">
          <i class="fa fa-heart-o fa-2x"></i>
        </button><dt>
      <% end %>
      <br>
  <% end %>
  </dl>
</p>

<%= link_to 'Back', destinations_path %>